version: '3'

services:
  noderepository:
    image: matiasberardi/iascrepository
    ports:
      - "3000:3000"
      - "4000:4000"
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 10s
    networks:
      - repository
  nodeapp:
   image: matiasberardi/iasc
   ports:
     - "5000:5000"
   depends_on:
     - noderepository
   deploy:
     replicas: 1
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s
   networks: 
    - balance
    - repository
  
  proxy:
    image: matiasberardi/nginx_loadbalancer
    ports:
      - "80:80"
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay
  repository: