version: '3'

services:
  nodeapp:
   image: matiasberardi/iasc
   ports:
     - 5000:5000
   deploy:
     replicas: 2
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s
   networks: 
    - balance 
  
  proxy:
    image: matiasberardi/nginx_loadbalancer
    ports:
      - 80:80
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay